services:
  postgres-keycloak:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${DB_PASSWORD_KEYCLOAK}
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak-dev
    # El comando --import-realm busca archivos en /opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${DB_PASSWORD_KEYCLOAK}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "7080:8080"
    volumes:
      # Mapeamos tu carpeta local donde está el JSON al contenedor
      - ./keycloak-config:/opt/keycloak/data/import
    depends_on:
      - postgres-keycloak

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:mysql}
      MYSQL_DATABASE: orders_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  config-server: 
    build: ./config-server
    container_name: config-server
    environment:
      - JAVA_OPTS=-Xms32m -Xmx64m
    ports:
      - "8888:8888"
    depends_on:
      - keycloak

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    environment:
      - JAVA_OPTS=-Xms32m -Xmx64m 
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      - JAVA_OPTS=-Xms32m -Xmx64m
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
  msvc-product:
    build: ./msvc-product
    container_name: msvc-product
    environment:
      - JAVA_OPTS=-Xms32m -Xmx64m
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mysql
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
      - mysql
  msvc-order:
    build: ./msvc-order
    container_name: msvc-order
    environment:
      - JAVA_OPTS=-Xms32m -Xmx64m
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mysql
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
      - mysql

volumes:
  keycloak_pgdata:
  mysql_data: